name: base
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - adwaita-icon-theme=49.0=unix_0
  - affine=2.4.0=pyhd8ed1ab_1
  - aiobotocore=2.22.0=pyhd8ed1ab_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aioitertools=0.12.0=pyhd8ed1ab_1
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alsa-lib=1.2.14=hb9d3cd8_0
  - altair=5.5.0=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - aom=3.9.1=hac33072_0
  - archspec=0.2.5=pyhd8ed1ab_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - asciitree=0.3.3=py_2
  - async-lru=2.0.5=pyh29332c3_0
  - async_generator=1.10=pyhd8ed1ab_2
  - at-spi2-atk=2.38.0=h0630a04_3
  - at-spi2-core=2.40.3=h0630a04_0
  - atk-1.0=2.38.0=h04ea711_2
  - attr=2.5.2=h39aace5_0
  - aws-c-auth=0.9.1=h7ca4310_7
  - aws-c-cal=0.9.10=h346e085_1
  - aws-c-common=0.12.5=hb03c661_1
  - aws-c-compression=0.3.1=h7e655bb_8
  - aws-c-event-stream=0.5.6=h3cb25bf_6
  - aws-c-http=0.10.7=hc5c8343_4
  - aws-c-io=0.23.3=ha76f1cc_3
  - aws-c-mqtt=0.13.3=h3a25ec9_10
  - aws-c-s3=0.10.1=hcb69869_2
  - aws-c-sdkutils=0.2.4=h7e655bb_3
  - aws-checksums=0.2.7=h7e655bb_4
  - aws-crt-cpp=0.35.2=h2ceb62e_4
  - aws-sdk-cpp=1.11.606=hd6e39bc_7
  - azure-core-cpp=1.16.1=h3a458e0_0
  - azure-identity-cpp=1.13.2=h3a5f585_1
  - azure-storage-blobs-cpp=12.15.0=h2a74896_1
  - azure-storage-common-cpp=12.11.0=h3d7a050_1
  - azure-storage-files-datalake-cpp=12.13.0=hf38f1be_1
  - babel=2.17.0=pyhd8ed1ab_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blinker=1.9.0=pyhff2d567_0
  - blosc=1.21.6=he440d0b_1
  - bokeh=3.8.1=pyhd8ed1ab_0
  - boltons=25.0.0=pyhd8ed1ab_0
  - boto3=1.37.3=pyhd8ed1ab_0
  - botocore=1.37.3=pyge310_1234567_0
  - bottleneck=1.4.2=py312hc0a28a1_0
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.2.0=h41a2e66_0
  - brotli-bin=1.2.0=hf2c8021_0
  - brotli-python=1.2.0=py312h67db365_0
  - brunsli=0.1=hd1e3526_2
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - c-blosc2=2.22.0=h4cfbee9_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachey=0.2.1=pyh9f0ad1d_0
  - cairo=1.18.4=h3394656_0
  - cartopy=0.25.0=py312hf79963d_1
  - certifi=2025.11.12=pyhd8ed1ab_0
  - certipy=0.2.2=pyhd8ed1ab_0
  - cffi=2.0.0=py312h460c074_1
  - cftime=1.6.4=py312h4f23490_2
  - charls=2.4.2=h59595ed_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - chartlets=0.1.6=pyhd8ed1ab_0
  - click=8.3.1=pyh707e725_0
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - cloudpickle=3.1.2=pyhd8ed1ab_0
  - cmocean=4.0.3=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorcet=3.1.0=pyhd8ed1ab_1
  - colorspacious=1.1.2=pyhecae5ae_1
  - comm=0.2.3=pyhe01879c_0
  - conda=25.9.1=py312h7900ff3_0
  - conda-libmamba-solver=25.4.0=pyhd8ed1ab_0
  - conda-package-handling=2.4.0=pyh7900ff3_2
  - conda-package-streaming=0.12.0=pyhd8ed1ab_0
  - contourpy=1.3.3=py312hd9148b4_3
  - cpp-expected=1.3.1=h171cf75_0
#  - cpython=3.13.7=py313hd8ed1ab_100
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - cytoolz=1.1.0=py312h4c3975b_1
  - dask=2025.11.0=pyhcf101f3_0
  - dask-core=2025.11.0=pyhcf101f3_0
  - dask-gateway=2025.4.0=pyha7f0ed4_2
  - dask-image=2025.11.0=pyhd8ed1ab_0
  - dask-labextension=7.0.0=pyhd8ed1ab_1
  - datashader=0.18.2=pyhd8ed1ab_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.3.1=pyhd8ed1ab_0
  - distributed=2025.11.0=pyhcf101f3_0
  - distro=1.9.0=pyhd8ed1ab_1
  - double-conversion=3.3.1=h5888daf_0
  - epoxy=1.5.10=hb03c661_2
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fasteners=0.19=pyhd8ed1ab_1
  - fiona=1.10.1=py312h02b19dd_3
  - fmt=12.0.0=h2b0788b_0
  - folium=0.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py312h8a5da7c_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=ha770c72_0
  - freexl=2.0.0=h9dce30a_2
  - fribidi=1.0.16=hb03c661_0
  - frozendict=2.4.7=py312h4c3975b_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gdal=3.10.3=py312hf50df08_26
  - gdk-pixbuf=2.44.4=h2b0a6b4_0
  - geopandas=1.1.1=pyhd8ed1ab_1
  - geopandas-base=1.1.1=pyha770c72_1
  - geos=3.14.1=h480dda7_0
  - geotiff=1.7.4=h1000f5c_4
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - glib-tools=2.86.1=hf516916_2
  - glog=0.7.1=hbabe93e_0
  - graphite2=1.3.14=hecca717_2
  - graphviz=14.0.4=h87b6fe6_0
  - gtk3=3.24.43=h993cebd_6
  - gts=0.7.6=h977cf35_4
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - h5netcdf=1.7.3=pyhd8ed1ab_0
  - h5py=3.15.1=nompi_py312ha4f8f14_100
  - harfbuzz=12.2.0=h15599e2_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - heapdict=1.0.1=pyhd8ed1ab_2
  - hicolor-icon-theme=0.17=ha770c72_2
  - holoviews=1.22.0=pyhd8ed1ab_1
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hvplot=0.12.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - imagecodecs=2025.11.11=py312ha08ed9d_0
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipyleaflet=0.20.0=pyhd8ed1ab_0
  - ipython_genutils=0.2.0=pyhd8ed1ab_2
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jdcal=1.4.1=py_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - json-c=0.18=h6688a6e_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py312h7900ff3_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter-pluto-proxy=0.1.2=pyhd8ed1ab_0
  - jupyter-server-mathjax=0.2.6=pyhbbac1ac_2
  - jupyter-server-proxy=4.4.0=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_leaflet=0.20.0=pyhd8ed1ab_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterhub-base=5.3.0=pyhda7c55b_0
  - jupyterhub-singleuser=5.3.0=h4422900_0
  - jupyterlab-git=0.51.2=pyhd8ed1ab_0
  - jupyterlab-myst=2.4.2=pyhd8ed1ab_1
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - jxrlib=1.1=hd590300_3
  - kerchunk=0.2.7=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py312h0a2e395_2
  - krb5=1.21.3=h659f571_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.45=h1aa0949_0
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.4=h3f801dc_0
  - libarchive=3.8.2=gpl_h7be2006_100
  - libarrow=22.0.0=h773bc41_4_cpu
  - libarrow-acero=22.0.0=h635bf11_4_cpu
  - libarrow-compute=22.0.0=h8c2c5c3_4_cpu
  - libarrow-dataset=22.0.0=h635bf11_4_cpu
  - libarrow-substrait=22.0.0=h3f74fd7_4_cpu
  - libavif16=1.3.0=h6395336_2
  - libblas=3.11.0=1_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=h09219d5_0
  - libbrotlidec=1.2.0=hd53d788_0
  - libbrotlienc=1.2.0=h02bd7ab_0
  - libcblas=3.11.0=1_h0358290_openblas
  - libclang-cpp21.1=21.1.5=default_h99862b1_1
  - libclang13=21.1.5=default_h746c552_1
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libegl-devel=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgd=2.3.3=h6f5c62b_11
  - libgdal-core=3.10.3=hd23061b_26
  - libgdal-jp2openjpeg=3.10.3=hdd07572_26
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libgl-devel=1.7.0=ha4b6fd6_2
  - libglib=2.86.1=h32235b2_2
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libglx-devel=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h3288cfb_1
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libjxl=0.11.1=hf08fa70_5
  - libkml=1.3.0=haa4a5bd_1022
  - liblapack=3.11.0=1_h47877c9_openblas
  - libllvm21=21.1.5=hf7376ad_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libmamba=2.3.3=h09abcb8_1
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnetcdf=4.9.3=nompi_h11f7409_103
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopengl=1.7.0=ha4b6fd6_2
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=22.0.0=h7376487_4_cpu
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=18.0=h3675c94_0
  - libprotobuf=6.31.1=h49aed37_2
  - libre2-11=2025.11.05=h7b12aa8_0
  - librsvg=2.60.0=h61e6d4b_0
  - librttopo=1.1.0=h46dd2a8_20
  - libsodium=1.0.20=h4ab18f5_0
  - libsolv=0.7.35=h9463b59_0
  - libspatialite=5.1.0=gpl_h2abfd87_119
  - libsqlite=3.51.0=hee844dc_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h9d88235_1
  - libutf8proc=2.11.1=hfe17d71_0
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.51.0=hb03c661_1
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.0=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxml2-devel=2.15.1=h26afc86_0
  - libxslt=1.1.43=h711ed8c_1
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - libzopfli=1.0.3=h9c3ff4c_0
  - linkify-it-py=2.0.3=pyhd8ed1ab_1
  - llvmlite=0.45.1=py312h7424e68_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.5=py312h3d67a73_0
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - mako=1.3.10=pyhd8ed1ab_0
  - mamba=2.3.3=heaf8479_1
  - mapclassify=2.10.0=pyhd8ed1ab_1
  - markdown=3.10=pyhcf101f3_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - mashumaro=3.17=pyhd8ed1ab_0
  - matplotlib=3.10.0=py312h7900ff3_0
  - matplotlib-base=3.10.0=py312hd3ec401_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdit-py-plugins=0.5.0=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - menuinst=2.4.1=py312h7900ff3_0
  - minizip=4.0.10=h05a5f5f_0
  - mistune=3.1.4=pyhcf101f3_0
  - msgpack-python=1.1.2=py312hd9148b4_1
  - multipledispatch=0.6.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - mystmd=1.6.4=pyhcf101f3_0
  - narwhals=2.12.0=pyhcf101f3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbdime=4.0.2=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nbgitpuller=1.2.2=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf4=1.7.3=nompi_py312hf6400b3_100
  - networkx=3.5=pyhe01879c_0
  - nlohmann_json=3.12.0=h54a6638_1
  - nlohmann_json-abi=3.12.0=h0f90c79_1
  - nodejs=24.9.0=heeeca48_0
  - nomkl=1.0=h5ca1d4c_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.62.1=py312h907b442_0
  - numcodecs=0.15.1=py312hf9745cd_0
  - numpy=1.26.4=py312heda63a1_0
  - oauthlib=3.3.1=pyhd8ed1ab_0
  - openeo=0.46.0=pyhd8ed1ab_0
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - orc=2.2.1=hd747db4_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pamela=1.2.0=pyhd8ed1ab_1
  - pandas=2.3.3=py312hf79963d_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - panel=1.8.3=pyhd8ed1ab_0
  - pango=1.56.4=hadf4263_0
  - param=2.3.0=pyhc455866_1
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.46=h1321c63_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=12.0.0=py312h0889fd4_0
  - pims=0.7=pyhd8ed1ab_1
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - planetary-computer=1.0.0=pyhd8ed1ab_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - proj=9.7.0=hb72c0af_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prometheus_client=0.22.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=22.0.0=py312h7900ff3_0
  - pyarrow-core=22.0.0=py312hc195796_0_cpu
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py312h4c3975b_3
  - pycparser=2.22=pyh29332c3_1
  - pyct=0.6.0=pyhd8ed1ab_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pyogrio=0.11.0=py312h02b19dd_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyproj=3.7.2=py312h9b6a7d9_2
  - pyshp=3.0.2=pyhd8ed1ab_0
  - pyside6=6.9.3=py312h9da60e5_1
  - pysocks=1.7.1=pyha55dd90_7
  - pystac=1.14.1=pyhd8ed1ab_0
  - pystac-client=0.9.0=pyhd8ed1ab_0
  - python=3.12.12=hd63d673_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-fastjsonschema=2.21.2=pyhe01879c_0
#  - python-gil=3.13.7=h4df99d1_100
  - python-graphviz=0.21=pyhbacfb6d_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyviz_comms=3.0.6=pyhd8ed1ab_0
  - pywavelets=1.9.0=py312h4f23490_2
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.3=h5c1c036_1
  - rasterio=1.4.3=py312h762fea3_3
  - rav1e=0.7.1=h8fae777_3
  - re2=2025.11.05=h5301d42_0
  - readline=8.2=h8c095d6_2
  - reproc=14.2.5.post0=hb9d3cd8_0
  - reproc-cpp=14.2.5.post0=h5888daf_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rioxarray=0.20.0=pyhd8ed1ab_0
  - ruamel.yaml=0.18.16=py312h4c3975b_0
  - ruamel.yaml.clib=0.2.14=py312h4c3975b_0
  - s2n=1.6.0=h8399546_1
  - s3fs=2025.10.0=pyhd8ed1ab_0
  - s3transfer=0.11.3=pyhd8ed1ab_0
  - scikit-image=0.25.2=py312hf79963d_2
  - scikit-learn=1.7.2=py312h4f0b9e3_0
  - scipy=1.16.3=py312h7a1785b_1
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=80.9.0=pyhff2d567_0
  - shapely=2.1.2=py312h383787d_2
  - simdjson=4.0.7=hb700be7_0
  - simpervisor=1.0.0=pyhd8ed1ab_1
  - six=1.17.0=pyhe01879c_1
  - slicerator=1.1.0=pyhd8ed1ab_1
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=h03e3b7b_1
  - snuggs=1.4.7=pyhd8ed1ab_2
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - sqlite=3.51.0=heff268d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - streamz=0.6.4=pyhd8ed1ab_1
  - svt-av1=3.1.2=hecca717_0
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tblib=3.2.2=pyhcf101f3_0
  - terminado=0.18.1=pyh0d859eb_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2025.10.16=pyhd8ed1ab_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_ha0e22de_103
  - toolz=1.1.0=pyhd8ed1ab_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - traittypes=0.2.3=pyh332efcf_0
  - truststore=0.10.3=pyhe01879c_0
  - types-python-dateutil=2.9.0.20250822=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - uc-micro-py=1.0.3=pyhd8ed1ab_1
  - ujson=5.11.0=py312h8285ef7_1
  - unicodedata2=17.0.0=py312h4c3975b_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wayland=1.24.0=hd6090a7_1
  - webencodings=0.5.1=pyhd8ed1ab_3
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - wrapt=1.17.3=py312h4c3975b_1
  - xarray=2024.11.0=pyhd8ed1ab_0
  - xarray-eopf=0.2.2=pyhd8ed1ab_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xcube=1.12.0=pyhd8ed1ab_0
  - xcube-eopf=0.3.0=pyhd8ed1ab_0
  - xcube-resampling=0.2.0=pyhd8ed1ab_0
#  - xcube-resampling>=0.3.0
  - xcube-stac=1.1.1=pyhd8ed1ab_0
  - xerces-c=3.3.0=h988505b_0
  - xkeyboard-config=2.46=hb03c661_0
  - xmltodict=1.0.2=pyhcf101f3_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xyzservices=2025.10.0=pyhd8ed1ab_0
  - yaml=0.2.5=h280c20c_3
  - yaml-cpp=0.8.0=h3f2d84a_0
  - zarr=2.18.7=pyhd8ed1ab_0
  - zeromq=4.3.5=h3989a48_8
  - zfp=1.0.1=h909a3a2_3
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstandard=0.25.0=py312h5253ce2_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - aiohttp==3.13.2
      - alembic==1.17.2
      - anyio==4.11.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - cryptography==46.0.3
      - debugpy==1.8.17
      - frozenlist==1.7.0
      - greenlet==3.2.4
      - ipykernel==7.1.0
      - ipython==9.7.0
      - jsonschema-specifications==2025.9.1
      - jupyterhub==5.4.2
      - jupyterlab==4.4.10
      - jupyterlab-server==2.28.0
      - lark==1.3.1
      - libmambapy==2.3.3
      - markupsafe==3.0.3
      - multidict==6.6.3
      - nbclassic==1.3.3
      - nbconvert==7.16.6
      - notebook==7.4.7
      - prometheus-client==0.23.1
      - propcache==0.3.1
      - psutil==7.1.3
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - rpds-py==0.29.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.44
      - tomli==2.3.0
      - tornado==6.4.2
      - typing-inspection==0.4.2
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - websocket-client==1.9.0
      - yarl==1.22.0
prefix: /opt/conda
